set number
set tabstop=2
set shiftwidth=2
set hlsearch
set nocompatible
set history=10000
hi NonText ctermfg=black guifg=black   
syntax on
filetype on
au BufRead,BufNewFile *.stc setfiletype cel
au BufRead,BufNewFile *.lp setfiletype cplexlp
au BufRead,BufNewFile *.acts setfiletype oldowanActs
au BufRead,BufNewFile *.cl setf opencl
colorscheme desert
nmap - $
ino jj <esc>
cno jj <c-c>
cno <c-j> <down>
cno <c-k> <up>
cno <c-h> <left>
cno <c-l> <right>

if has("multi_byte")
  if &termencoding == ""
    let &termencoding = &encoding
  endif
  set encoding=utf-8
  setglobal fileencoding=utf-8
  "setglobal bomb
  set fileencodings=ucs-bom,utf-8,latin1
endif

" modify selected text using combining diacritics
command! -range -nargs=0 Overline        call s:CombineSelection(<line1>, <line2>, '0305')
command! -range -nargs=0 Underline       call s:CombineSelection(<line1>, <line2>, '0332')
command! -range -nargs=0 DoubleUnderline call s:CombineSelection(<line1>, <line2>, '0333')
command! -range -nargs=0 Strikethrough   call s:CombineSelection(<line1>, <line2>, '0336')

function! s:CombineSelection(line1, line2, cp)
  execute 'let char = "\u'.a:cp.'"'
  execute a:line1.','.a:line2.'s/\%V[^[:cntrl:]]/&'.char.'/ge'
endfunction

vnoremap st :Strikethrough<CR>

autocmd Filetype python setlocal expandtab tabstop=4 shiftwidth=4
set directory=~/.vim/swapfiles/
